name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0

      - name: Initial Infra - Terraform Format
        id: tf-fmt
        run: terraform fmt -check --recursive

      - name: Terraform Init
        id: tf-init
        run: terraform init

      - name: Terraform Plan
        id: tf-plan
        run: terraform plan -no-color
        continue-on-error: true # Allow to display the errors on next step

      - uses: actions/github-script@0.9.0
        env:
          PLAN: "terraform\n${{ steps.tf-plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.tf-fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.tf-init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.tf-plan.outcome }}\`
            <details><summary>Show Plan</summary>
            <pre><code>${process.env.PLAN}</code></pre>
            </details>
            Pusher: @${{ github.actor }}, Action: ${{ github.event_name }}`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Terraform Plan Status
        if: steps.tf-plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
